### ISSUE TITLE
Allow Outputs of Other Sheets/Comands

### ISSUE THREAD

**Issue by evairmarinho** [aws-samples/aws-auto-inventory#11]
I would like to better document my inventory, not all boto3 client actions return details of my resources. I would like it to be possible to use outputs from other spreadsheets to generate spreadsheets with more details of AWS resources.

Possible `config.yaml`

```yml
---
Sheets: &sheets
  - name: EKSClusterNames
    service: eks
    function: list_clusters

  - name: EKSClusterDetails
    service: eks
    function: describe_cluster
    output_parameter: EKSClusterNames # loop the client action based in EKS Cluster Name list

inventories:
  - name: aws-test
    aws:
      profile: aws-test
      region:
        - us-east-1
        - sa-east-1
    excel:
      transpose: false
    sheets: *sheets
```
